version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
  - source: /bundle.js
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ec2-user
    group: apache
hooks:
  BeforeInstall:
    - location: install_deps.sh
  AfterInstall:
    - location: start_svc.sh
      timeout: 180