version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - npm version
  pre_build:
    on-failure: ABORT
    commands:
      - npm version
      - ls
      - npm ci
  build:
    on-failure: ABORT
    commands:
      - npm run build
  post_build:
    on-failure: ABORT
    commands:
      - cp dist/bundle.js public/
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
  discard-paths: yes
  secondary-artifacts:
    ec2:
      files:
        - 'public/*'
      name:  chuck-app-ec2-artifact
    bundleOnly:
      files:
        - dist/
      name:  chuck-app-bundle-only-artifact
cache:
  paths:
    - /root/.npm/**/*
