version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - npm version
  pre_build:
    on-failure: ABORT
    commands:
      - npm version
      - ls
      - npm ci
  build:
    on-failure: ABORT
    commands:
      - npm run build
  post_build:
    on-failure: ABORT
    commands:
      - cp dist/bundle.js public/
artifacts:
  files:
    - '**/*'
  base-directory: 'public'
  discard-paths: yes

cache:
  paths:
    - /root/.npm/**/*
